#数据库
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#
#  #端口
#  server:
#    port: 8080


#tk-Mybatis
mybatis:
  #实体类的存放路径
  type-aliases-package: com.aishang.shop_back2020.po
  mapper-locations: classpath:mapper/*.xml
  # spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl